version: "3.1"

services:
  gatsby:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
    ports: ["127.0.0.1:8000:8000"]
    container_name: personal_page
